### ISSUE TITLE
netfx-4.7.1-devpack exit code -1073741819

### ISSUE THREAD

**Issue by rgl** [jberezanski/ChocolateyPackages#22]
When installing `netfx-4.7.1-devpack` from a [vagrant environment](https://github.com/rgl/jenkins-vagrant) the package exit code is `-1073741819` even thou it install successfully, do you have any idea why? The install logs don't seem to have any error at all.

Can you modify the package `ChocolateyInstall.ps1` to include that exit code as a success exit code?

As a note, `netfx-4.7-devpack` installs without a problem.

Anyhow, I've updated the `ChocolateyInstall.ps1` file to also include that exit code as sucess. Here's how I'm installing a modified version of the nupkg:

```powershell
# NB we have to install netfx-4.7.1-devpack manually, because for some odd reason,
#    the setup is returning the -1073741819 exit code even thou it installs
#    successfully.
$archiveUrl = 'https://packages.chocolatey.org/netfx-4.7.1-devpack.4.7.2558.0.nupkg'
$archiveHash = 'e293769f03da7a42ed72d37a92304854c4a61db279987fc459d3ec7aaffecf93'
$archiveName = Split-Path $archiveUrl -Leaf
$archivePath = "$env:TEMP\$archiveName.zip"
Write-Host 'Downloading the netfx-4.7.1-devpack package...'
Invoke-WebRequest $archiveUrl -UseBasicParsing -OutFile $archivePath
$archiveActualHash = (Get-FileHash $archivePath -Algorithm SHA256).Hash
if ($archiveHash -ne $archiveActualHash) {
    throw "$archiveName downloaded from $archiveUrl to $archivePath has $archiveActualHash hash witch does not match the expected $archiveHash"
}
Expand-Archive $archivePath "$archivePath.tmp"
Push-Location "$archivePath.tmp"
Remove-Item -Recurse _rels,package,*.xml
Set-Content -Encoding Ascii `
    tools/ChocolateyInstall.ps1 `
    ((Get-Content tools/ChocolateyInstall.ps1) -replace '0, # success','0,-1073741819, # success')
choco pack
choco install -y netfx-4.7.1-devpack -Source $PWD
Pop-Location
```

**Comment by jberezanski** [comment]
-1073741819  is hex 0xc0000005, which is STATUS_ACCESS_VIOLATION - an attempt to access invalid memory. This usually indicates a bug in the application or a corruption of some operating system component; it might also be a hardware/driver/virtualization error. I'm not comfortable with adding it as a success code.

I can see you are installing .NET 4.7.1 first. Do you reboot the machine after that? If not, the system might be in an unpredictable, unstable state until you do.

Apart from that, I suggest the following troubleshooting approaches:
- reduce the problem by disabling all other earlier provisioning steps, one by one
- execute your provisioning steps manually, outside of Vagrant, using a known good operating system image (for example, the Microsoft-provided evaluation one)
- execute your provisioning steps manually after Vagrant provisions a clean machine

**Comment by jberezanski** [comment]
You may also want to look at the Application event log to see whether the application crash gets logged by the operating system (and to see exactly which process crashes).

**Comment by snarky** [comment]
i have the same problem with chef + chocolatey_package

```
Failed` Chef Client run aa00acac-a4cd-4233-8880-c39ceca7914f in 33.249556 seconds.
 Exception type: Mixlib::ShellOut::ShellCommandFailed
 Exception message: chocolatey[netfx-4.7.1-devpack] (tsbuild::prerequisites line 37) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[install package netfx-4.7.1-devpack] (c:/chef/cache/cookbooks/chocolatey/providers/default.rb line 132) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '-1073741819'
---- Begin output of "C:\ProgramData\chocolatey/bin/choco" install -y  netfx-4.7.1-devpack ----
STDOUT: Chocolatey v0.10.8
Installing the following packages:
netfx-4.7.1-devpack
By installing you accept licenses for the packages.

Progress: Downloading netfx-4.7.1-devpack 4.7.2558.0... 15%
Progress: Downloading netfx-4.7.1-devpack 4.7.2558.0... 47%
Progress: Downloading netfx-4.7.1-devpack 4.7.2558.0... 79%
Progress: Downloading netfx-4.7.1-devpack 4.7.2558.0... 100%

netfx-4.7.1-devpack v4.7.2558.0 [Approved]
netfx-4.7.1-devpack package files install completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Hashes match.
Hashes match.
Installing netfx-4.7.1-devpack...
ERROR: Running ["C:\Windows\TEMP\chocolatey\netfx-4.7.1-devpack\4.7.2558.0\NDP471-DevPack-ENU.exe" /Quiet /NoRestart /Log "C:\Windows\TEMP\chocolatey\netfx-4.7.1-devpack.log" ] was not successful. Exit code was '-1073741819'. See log for possible error messages.
The install of netfx-4.7.1-devpack was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\netfx-4.7.1-devpack\tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - netfx-4.7.1-devpack (exited -1073741819) - Error while running 'C:\ProgramData\chocolatey\lib\netfx-4.7.1-devpack\tools\ChocolateyInstall.ps1'.
 See log for details.
STDERR: 
---- End output of "C:\ProgramData\chocolatey/bin/choco" install -y  netfx-4.7.1-devpack ----
Ran "C:\ProgramData\chocolatey/bin/choco" install -y  netfx-4.7.1-devpack returned -1073741819
```

If you take a look to the line:

```
ERROR: Running ["C:\Windows\TEMP\chocolatey\netfx-4.7.1-devpack\4.7.2558.0\NDP471-DevPack-ENU.exe" /Quiet /NoRestart /Log "C:\Windows\TEMP\chocolatey\netfx-4.7.1-devpack.log" ] was not successful. Exit code was '-1073741819'. See log for possible error messages.
```

And check the indicated log file "C:\Windows\TEMP\chocolatey\netfx-4.7.1-devpack.log", you can see on the last line `Shutting down, exit code: 0xbc2` which correspond to error code **3010**

https://msdn.microsoft.com/en-us/library/windows/desktop/ms681386(v=vs.85).aspx#ERROR_SUCCESS_REBOOT_REQUIRED
**ERROR_SUCCESS_REBOOT_REQUIRED**
    **3010 (0xBC2)**
    The requested operation is successful. Changes will not be effective until the system is rebooted.

**Comment by jeremygaither** [comment]
I have the same problem when building with Packer on AWS.

**Comment by OwenGr** [comment]
This is also happening with netfx-4.7.2-devpack

```
Chocolatey v0.10.11
    azure-arm: Installing the following packages:
    azure-arm: netfx-4.7.2-devpack
    azure-arm: By installing you accept licenses for the packages.
    azure-arm: Progress: Downloading netfx-4.7.2-devpack 4.7.2.0... 100%
    azure-arm:
    azure-arm: netfx-4.7.2-devpack v4.7.2.0 [Approved]
    azure-arm: netfx-4.7.2-devpack package files install completed. Performing other installation steps.
    azure-arm: Downloading netfx-4.7.2-devpack 64 bit
    azure-arm:   from 'https://download.microsoft.com/download/5/F/E/5FE505D0-E753-4F1A-B8D6-D9E73C0C28C7/NDP472-DevPack-ENU.exe'
    azure-arm: Progress: 100% - Completed download of C:\Users\packer\AppData\Local\Temp\chocolatey\netfx-4.7.2-devpack\4.7.2.0\NDP472-DevPack-ENU.exe (92.82 MB).
    azure-arm: Download of NDP472-DevPack-ENU.exe (92.82 MB) completed.
    azure-arm: Hashes match.
    azure-arm: Installing netfx-4.7.2-devpack...
    azure-arm: ERROR: Running ["C:\Users\packer\AppData\Local\Temp\chocolatey\netfx-4.7.2-devpack\4.7.2.0\NDP472-DevPack-ENU.exe" /Quiet /NoRestart /Log "C:\Users\packer\AppData\Local\Temp\chocolatey\netfx-4.7.2-devpack_4.7.2_20180515205800.log" ] was not successful. Exit code was '-1073741819'. See log for possible errormessages.
    azure-arm:   netfx-4.7.2-devpack can be automatically uninstalled.
    azure-arm: The install of netfx-4.7.2-devpack was NOT successful.
```
