### ISSUE TITLE
Choco install `visualstudio2017-workload-vctools` no longer works on `windows-2019`

### ISSUE THREAD

**Issue by collinpeters** [jberezanski/ChocolateyPackages#97]
Cross-posting this from https://github.com/actions/virtual-environments/issues/2857

I am having the same issue as the author there. Specifically that the install fails on the GitHub Actions Windows 2019 image which is itself unchanged.

Please see that issue for full details but I will copy/paste the error here.
```
WARNING: Found 2 still running Visual Studio installer processes:
WARNING: [436] vs_bootstrapper
WARNING: [3104] vs_setup_bootstrapper
WARNING: Waiting for the processes to finish...
visualstudio2017buildtools has been installed.
  visualstudio2017buildtools may be able to be automatically uninstalled.
 The install of visualstudio2017buildtools was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

visualstudio2017-workload-vctools v1.3.2 [Approved]
visualstudio2017-workload-vctools package files install completed. Performing other installation steps.
ERROR: Unable to detect any supported Visual Studio product. You may try passing --installPath or both --productId and --channelId parameters.
The install of visualstudio2017-workload-vctools was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2017-workload-vctools\tools\ChocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 5/6 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Installed:
 - visualstudio2017buildtools v15.9.33.0
 - dotnetfx v4.8.0.20190930
 - chocolatey-visualstudio.extension v1.9.0
 - visualstudio-installer v2.0.1
 - chocolatey-dotnetfx.extension v1.0.1

Failures
 - visualstudio2017-workload-vctools (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\visualstudio2017-workload-vctools\tools\ChocolateyInstall.ps1'.
```

**Comment by jberezanski** [comment]
As I wrote in that issue. in order to try to determine the cause, I need:
- the full Chocolatey log: $Env:ChocolateyInstall\logs\chocolatey.log
- the Visual Studio log files (there will be a lot of them): $Env:TEMP\chocolatey\dd_*.log

**Comment by collinpeters** [comment]
I'm not a Windows guy but I just used GitHub Actions using the workflow file in the other ticket and it looks like the run has all the files you need.

Failed run with artifact attached with logs: https://github.com/collinpeters/win-vs-test/actions/runs/643660346

For reference the workflow file is:
```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Env
        run: |
          gci env:* | sort-object name

      - name: Set up Visual C Build Tools Workload for Visual Studio 2017 Build Tools
        run: choco install visualstudio2017-workload-vctools

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: |
            C:\ProgramData\chocolatey\logs
            C:\Users\runneradmin\AppData\Local\Temp\chocolatey\dd_*.log
```
